### ISSUE TITLE
How many GPUs do you use during training?

### ISSUE THREAD

**Issue by huaer9258** [ZheC/Realtime_Multi-Person_Pose_Estimation#100]
Hey Zhe Cao~    I have a question about how many GPUs do you use when you are training.  The trained model "pose_iter_440000.caffemodel" you provided (use batch size 10 and iterations 44000 in your solver.prototxt) is trained using 1 GPU?   I didn't find this information in your paper and your oral presentation ppt. I'll appreciate it if you can tell me the training details about that. @ZheC

**Comment by ZheC** [comment]
We use two TitanX GPU for training the model. Thanks

**Comment by huaer9258** [comment]
Thanks for your reply!
