### ISSUE TITLE
matcaffe

### ISSUE THREAD

**Issue by xiangweifeng** [ZheC/Realtime_Multi-Person_Pose_Estimation#101]
W0927 13:12:01.708724 25361 net.hpp:41] DEPRECATED: ForwardPrefilled() will be removed in a future version. Use Forward().
F0927 13:12:01.723714 25361 pooling_layer.cu:212] Check failed: error == cudaSuccess (9 vs. 0)  invalid configuration argument
*** Check failure stack trace: ***
dell@dell-Precision-Tower-7910:/usr/local/MATLAB/R2016b/bin$
What's wrong with that?

**Comment by leodays** [comment]
@xiangweifeng Im am getting this error as well. How were you able to solve this?
