### ISSUE TITLE
How is "intermediate supervision" implemented? 

### ISSUE THREAD

**Issue by oujieww** [ZheC/Realtime_Multi-Person_Pose_Estimation#103]
How is "intermediate supervision" implemented? My understanding is that the eq. 5 is the equation that enforce the intermediate supervision. However, when I look at the prototxt, I found no clue of eq.5 inside.

Could anyone please explain for me?

**Comment by ds2268** [comment]
Intermediate supervision is implemented such that at the end of each stage you have loss to be computed instead of just at the end.
