### ISSUE TITLE
What is the center_map used for?

### ISSUE THREAD

**Issue by oujieww** [ZheC/Realtime_Multi-Person_Pose_Estimation#108]
In the CPM model and your model,I have find center_map.what is the center_map used for? in your demo there are 4 different scales to resize image and get heatmaps/pafs for 4 times.of course,this way can improve the performance,but i don't the reason.Please help me!Thanks.

**Comment by ZheC** [comment]
Sorry for my late response. 
The center map is for old experiments, it is not used anymore. I sliced the center map out in the proto file: https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/example_proto/pose_train_test.prototxt#L62-L77. 

Ideally, I should not generate it in the data_transformer.cpp
