### ISSUE TITLE
What's the meaning of the function float2bytes in genLMDB.py

### ISSUE THREAD

**Issue by Marcovaldong** [ZheC/Realtime_Multi-Person_Pose_Estimation#109]
I don't understand the meaning of the float2bytes function used when generating lmdb, and what is the meaning of matrix meta_data in genLMDB.py.

I'll appreciate for your reply.

**Comment by oujieww** [comment]
I have read those code ，i thank the joints and other information will be saved into mete_data

**Comment by xie-dongping** [comment]
The data is then decoded by ` src/caffe/cpm_data_transformer.cpp ` in their customized version of `caffe`
