### ISSUE TITLE
genANNO.m  Error: undefine function gasonMex

### ISSUE THREAD

**Issue by liaowang0125** [ZheC/Realtime_Multi-Person_Pose_Estimation#110]
I download the datasets and annotations,when I run genANNO.m,it shows

```
undefine function 'gasonMex'

error gason (line 53)
out = gasonMex( 'convert', in );

error CocoApi (line 61)
        coco.data=gason(fileread(annFile)); end

error getANNO (line 18)
    coco=CocoApi(annFile);
```

how to solve it?

**Comment by oujieww** [comment]
mex xx.c/cpp ，to make cpp in matlab

**Comment by liaowang0125** [comment]
Thank you! I have solved it;

**Comment by vrao9** [comment]
Even I'm getting the same error. Could you please elaborate the solution..
When I tried : mex gasonMex.cpp
I'm getting the following error:
```
Error using mex
   Creating library gasonMex.lib and object gasonMex.exp
gasonMex.obj : error LNK2019: unresolved external symbol "char const * __cdecl jsonStrError(int)"
(?jsonStrError@@YAPEBDH@Z) referenced in function mexFunction
gasonMex.obj : error LNK2019: unresolved external symbol "public: void __cdecl JsonAllocator::deallocate(void)"
(?deallocate@JsonAllocator@@QEAAXXZ) referenced in function "public: __cdecl JsonAllocator::~JsonAllocator(void)"
(??1JsonAllocator@@QEAA@XZ)
gasonMex.obj : error LNK2019: unresolved external symbol "int __cdecl jsonParse(char *,char * *,union JsonValue *,class
JsonAllocator &)" (?jsonParse@@YAHPEADPEAPEADPEATJsonValue@@AEAVJsonAllocator@@@Z) referenced in function mexFunction
gasonMex.mexw64 : fatal error LNK1120: 3 unresolved externals
```

**Comment by salvador-blanco** [comment]
I get the same error when I run genANNO.m

**Comment by salvador-blanco** [comment]
I found the gasonMex.cpp file, it is in the folder training/dataset/COCO/coco MatlabAPI/private
But I get the same error as @vrao9 
@vrao9 have you been able to solve it ?
```
Error using mex
   Creating library gasonMex.lib and object gasonMex.exp
gasonMex.obj : error LNK2019: unresolved external symbol "char const
* __cdecl jsonStrError(int)" (?jsonStrError@@YAPEBDH@Z) referenced in
function mexFunction
gasonMex.obj : error LNK2019: unresolved external symbol "public:
void __cdecl JsonAllocator::deallocate(void)"
(?deallocate@JsonAllocator@@QEAAXXZ) referenced in function "public:
__cdecl JsonAllocator::~JsonAllocator(void)"
(??1JsonAllocator@@QEAA@XZ)
gasonMex.obj : error LNK2019: unresolved external symbol "int __cdecl
jsonParse(char *,char * *,union JsonValue *,class JsonAllocator &)"
(?jsonParse@@YAHPEADPEAPEADPEATJsonValue@@AEAVJsonAllocator@@@Z)
referenced in function mexFunction
gasonMex.mexw64 : fatal error LNK1120: 3 unresolved externals
```

**Comment by salvador-blanco** [comment]
@liaowang0125 could you share on how did you manage to make it work.
The sasonMex.cpp is in a private folder so I am having issues trying to run it. Is this the correct way to do it? to run the gasonMex.cpp file ?

**Comment by vrao9** [comment]
I was not able to resolve it @salvador-blanco

**Comment by salvador-blanco** [comment]
@vrao9 
I was able to solve it, the solution is not optimal but it does the job
So if you open the gason.m, the function that calls gasonMex in the comments you will find:

> The following command compiles the parser (may require tweaking):
> %   mex('CXXFLAGS=\$CXXFLAGS -std=c++11 -Wall','-largeArrayDims',...
> %     'private/gasonMex.cpp','../common/gason.cpp',...
> %     '-I../common/','-outdir','private');

As it mentions you will need to adjust the path to the files gasonMex.cpp and ogason.cpp, etc.
In my case:
mex('CXXFLAGS=\$CXXFLAGS -std=c++11 -Wall','-largeArrayDims','dataset/COCO/coco/MatlabAPI/private/gasonMex.cpp','dataset/COCO/coco/common/gason.cpp','-Idataset/COCO/coco/common/','-outdir','private');

This will genarate a file "gasonMex.mexw64", in my case it was in the folder "....training/private"
I moved it into the "...training\dataset\COCO\coco\MatlabAPI\private"
Then I ran the getANNO script and it worked

I wonder what problems will come as we continue XD

**Comment by vrao9** [comment]
@salvador-blanco
Thanks for sharing the solution... I'll check how it works in my case...

**Comment by henanjun** [comment]
Thank you very much. I solve the the same problem with your solution. @salvador-blanco

**Comment by Ben-Park** [comment]
Thank you very much. I solve the same problem too.

**Comment by ybai62868** [comment]
@salvador-blanco @henanjun @Ben-Park I meet the same quesition and  I can not solve it. But I want to know it is about the version of matlab? Can you tell me which version of matlab when you running the code.

**Comment by ybai62868** [comment]
@salvador-blanco @henanjun @Ben-Park I meet the same quesition and I can not solve it. But I want to know whether it is about the version of matlab? Can you tell me which version of matlab when you running the code.

**Comment by henanjun** [comment]
My matlab verison is MATLAB 2016b. @ybai62868

**Comment by HovoTopTal** [comment]
1. Use `myCCompiler = mex.getCompilerConfigurations('C++','Selected')` in MATLAB Command Window to know which compiler is used in mex compiler configuration for C++. If not installed do `mex -setup C++` to setup compiler for C++ (see Mathworks website for the details). You can see here the parameter `Version: '15.0'` in my case the version is 15 (Microsoft Visual C++ 2017).
2. For Matlab, add coco/MatlabApi to the Matlab path with `addpath <dir>\cocoapi-master\MatlabAPI` where `<dir>` is the path `containing cocoapi-master` folder.
3. Run the code:
`mex('CXXFLAGS=\$CXXFLAGS -std=c++<Version>-Wall','-largeArrayDims',...
     'private/gasonMex.cpp','../common/gason.cpp',...
     '-I../common/','-outdir','private');`
Where `<Version>` is the number of parameter `Version` of mex compiler configuration, in my case 15, i.e.:
`mex('CXXFLAGS=\$CXXFLAGS -std=c++15-Wall','-largeArrayDims',...
     'private/gasonMex.cpp','../common/gason.cpp',...
     '-I../common/','-outdir','private');`.
This should work, I tried, it works for me.

**Comment by moin59** [comment]
> @vrao9
> I was able to solve it, the solution is not optimal but it does the job
> So if you open the gason.m, the function that calls gasonMex in the comments you will find:
> 
> > The following command compiles the parser (may require tweaking):
> > %   mex('CXXFLAGS=$CXXFLAGS -std=c++11 -Wall','-largeArrayDims',...
> > %     'private/gasonMex.cpp','../common/gason.cpp',...
> > %     '-I../common/','-outdir','private');
> 
> As it mentions you will need to adjust the path to the files gasonMex.cpp and ogason.cpp, etc.
> In my case:
> mex('CXXFLAGS=$CXXFLAGS -std=c++11 -Wall','-largeArrayDims','dataset/COCO/coco/MatlabAPI/private/gasonMex.cpp','dataset/COCO/coco/common/gason.cpp','-Idataset/COCO/coco/common/','-outdir','private');
> 
> This will genarate a file "gasonMex.mexw64", in my case it was in the folder "....training/private"
> I moved it into the "...training\dataset\COCO\coco\MatlabAPI\private"
> Then I ran the getANNO script and it worked
> 
> I wonder what problems will come as we continue XD

**Comment by moin59** [comment]
Thanks, @salvador-blanco your instruction about the generated 'gasonMex.mexw64' file in "training/private" folder that should move to the "....\MatlabAPI\private" directory. 
Also, we can solve this problem by editing the 'gason.m' file and we don't need to move the gasonMex file. It will automatically generate the gasonMex file in  "....\MatlabAPI\private" directory. Just change the output directory for generating gasonMex file.

**>****write  '-outdir','dataset/COCO/coco/MatlabAPI/private'** **instead of** **'-outdir','private'**

>just copy this
mex('CXXFLAGS=$CXXFLAGS -std=c++11 -Wall','-largeArrayDims','dataset/COCO/coco/MatlabAPI/private/gasonMex.cpp','dataset/COCO/coco/common/gason.cpp','-Idataset/COCO/coco/common/','-outdir','dataset/COCO/coco/MatlabAPI/private');

**Comment by RajatGarg45** [comment]
'gasonMex.mexw64' file is already present in MatlabAPI\private directory in my case. Still getting the error message undefine function 'gasonMex' when trying to run extractThings.m
Kindly help. 
Also, when I try to compile gasonMex it gives a lot of errors.
error: 'mxCreateDoubleScalar' was not declared in this scope
       return mxCreateDoubleScalar(o.toNumber());
error: 'mxLOGICAL_CLASS' was not declared in this scope
     case mxLOGICAL_CLASS: return json<uint8_t,uint32_t>(S,(uint8_t*) A,n);
error: 'mxArrayToString' was not declared in this scope
     case mxCHAR_CLASS:    return json(S,mxArrayToString(M));
error: 'mwSize' was not declared in this scope
   mxArray *M; ushort *c; mwSize n[2]={1,strlen(str)};
error: 'n' was not declared in this scope
   M=mxCreateCharArray(2,n); c=(ushort*) mxGetData(M);

**Comment by RajatGarg45** [comment]
I tried to compile gasonMex.cpp but it throws following errors-

**Error using mex
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:
In function 'mxArray* json(const JsonValue&)':
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:40:47:
error: 'mxCreateDoubleScalar' was not declared in this scope
       return mxCreateDoubleScalar(o.toNumber());
                                               ^
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:
In function 'ostrm& json(ostrm&, const mxArray*)':
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:140:10:
error: 'mxLOGICAL_CLASS' was not declared in this scope
     case mxLOGICAL_CLASS: return json<uint8_t,uint32_t>(S,(uint8_t*) A,n);
          ^
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:141:58:
error: 'mxArrayToString' was not declared in this scope
     case mxCHAR_CLASS:    return json(S,mxArrayToString(M));
                                                          ^
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:
In function 'mxArray* mxCreateStringRobust(const char*)':
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:163:26:
error: 'mwSize' was not declared in this scope
   mxArray *M; ushort *c; mwSize n[2]={1,strlen(str)};
                          ^
E:\cocostuff\annotator\cocostuff10k-master\downloads\cocoApi\cocoapi-336d2a27c91e3c0663d2dcf0b13574674d30f88e\MatlabAPI\private\gasonMex.cpp:164:25:
error: 'n' was not declared in this scope
   M=mxCreateCharArray(2,n); c=(ushort*) mxGetData(M);**

Kindly help..

**Comment by akmal871026** [comment]
> mex xx.c/cpp ，to make cpp in matlab

Dear, how to make it? because I face the same problem

**Comment by BeauDoggie** [comment]
您好！，来信收到，尽快给您回复。
