### ISSUE TITLE
genLMDB ERROR:'Nonetype' has no attribute 'shape'

### ISSUE THREAD

**Issue by Destinyzs** [ZheC/Realtime_Multi-Person_Pose_Estimation#112]
when i execute this code: ` height = img.shape[0]`
Error shows: `AttributeError: 'NoneType' object has no attribute 'shape'`.
How can i solve it？

**Comment by Destinyzs** [comment]
i have solved it.thanks!

**Comment by salvador-blanco** [comment]
@Destinyzs 
Could you share the solution?

I have a similar problem 
```
Traceback (most recent call last):
  File "genLMDB.py", line 198, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 171, in writeLMDB
    img4ch = np.concatenate((img, meta_data, mask_miss[...,None], mask_all[...,None]), axis=2)
TypeError: 'NoneType' object has no attribute '__getitem__'

```

**Comment by Destinyzs** [comment]
@salvador-blanco 
I think there is a problem with some of the image properties what you want to store in the imdb.I vaguely remember this.I have forgot it..sorry

**Comment by bowrian** [comment]
> @destinyzs
> Could you share the solution?
> 
> I have a similar problem
> 
> ```
> Traceback (most recent call last):
>   File "genLMDB.py", line 198, in <module>
>     writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
>   File "genLMDB.py", line 171, in writeLMDB
>     img4ch = np.concatenate((img, meta_data, mask_miss[...,None], mask_all[...,None]), axis=2)
> TypeError: 'NoneType' object has no attribute '__getitem__'
> ```

Do you solve this problem?
