### ISSUE TITLE
annotation of keypoints

### ISSUE THREAD

**Issue by wuchichung** [ZheC/Realtime_Multi-Person_Pose_Estimation#114]
as i know, there are 18 joints detected in the project and i just want to know what are they ?

**Comment by wuchichung** [comment]
i have hacked the problem by this 

![screen shot 2017-11-09 at 18 04 22](https://user-images.githubusercontent.com/13150356/32599809-989afc26-c578-11e7-9a65-2f11ecb1d90a.png)

![Uploading cook_hero.png…]()

and get the following result ：

0  : noise
1  : chest
2  : left shoulder
3  : left elbow
4  : left wrist
5  : right shoulder
6  : right elbow
7  : right wrist
8  : left tuttocks
9  : left knee
10 : left ankle
11 : right tuttocks
12 : right knee
13 : right ankle
14 : left eye
15 : right eye
16 : left ear
17 : right ear

but i am still confused about what are the symbol for label 18 and label 19

**Comment by anatolix** [comment]
18 is "background". There is no 19th if you calculating from zero.

**Comment by youansheng** [comment]
Another label point is caculated from chest and tuttocks. Read paper carefully!!!
