### ISSUE TITLE
eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() 

### ISSUE THREAD

**Issue by Destinyzs** [ZheC/Realtime_Multi-Person_Pose_Estimation#116]
when i use my own data to train，i meet the following misstakes.Can anybody help me?
```
F1113 05:19:21.525831 15306 eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() 
*** Check failure stack trace: ***
    @     0x7f0c1f867daa  (unknown)
    @     0x7f0c1f867ce4  (unknown)
    @     0x7f0c1f8676e6  (unknown)
    @     0x7f0c1f86a687  (unknown)
    @     0x7f0c1ff199dd  caffe::EltwiseLayer<>::Reshape()
    @     0x7f0c1fec80ac  caffe::Net<>::Init()
    @     0x7f0c1fec8f25  caffe::Net<>::Net()
    @     0x7f0c1fed16ba  caffe::Solver<>::InitTrainNet()
    @     0x7f0c1fed27bc  caffe::Solver<>::Init()
    @     0x7f0c1fed2aea  caffe::Solver<>::Solver()
    @     0x7f0c2003bbe3  caffe::Creator_SGDSolver<>()
    @           0x40f0fe  caffe::SolverRegistry<>::CreateSolver()
    @           0x408134  train()
    @           0x405b3c  main
    @     0x7f0c1e873f45  (unknown)
    @           0x4063ab  (unknown)
    @              (nil)  (unknown)

```

**Comment by Destinyzs** [comment]
@ZheC  can you help me?

**Comment by moin59** [comment]
Hi, @destinyzs did you solved it? I got same error too

**Comment by weilanShi** [comment]
> when i use my own data to train，i meet the following misstakes.Can anybody help me?
> 
> ```
> F1113 05:19:21.525831 15306 eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() 
> *** Check failure stack trace: ***
>     @     0x7f0c1f867daa  (unknown)
>     @     0x7f0c1f867ce4  (unknown)
>     @     0x7f0c1f8676e6  (unknown)
>     @     0x7f0c1f86a687  (unknown)
>     @     0x7f0c1ff199dd  caffe::EltwiseLayer<>::Reshape()
>     @     0x7f0c1fec80ac  caffe::Net<>::Init()
>     @     0x7f0c1fec8f25  caffe::Net<>::Net()
>     @     0x7f0c1fed16ba  caffe::Solver<>::InitTrainNet()
>     @     0x7f0c1fed27bc  caffe::Solver<>::Init()
>     @     0x7f0c1fed2aea  caffe::Solver<>::Solver()
>     @     0x7f0c2003bbe3  caffe::Creator_SGDSolver<>()
>     @           0x40f0fe  caffe::SolverRegistry<>::CreateSolver()
>     @           0x408134  train()
>     @           0x405b3c  main
>     @     0x7f0c1e873f45  (unknown)
>     @           0x4063ab  (unknown)
>     @              (nil)  (unknown)
> ```

did you solved it? I got same error .....
