### ISSUE TITLE
Can not understanding the math in render_pose_coco_parts kernel function.

### ISSUE THREAD

**Issue by KeyKy** [ZheC/Realtime_Multi-Person_Pose_Estimation#12]
@ZheC Could you explain the follow code? Does render_pose_coco_parts only draw color on frame.data_for_mat? Thanks!

        if(value_a > threshold && value_b > threshold){
          //  -------------------
          // |
          // |            .(x_a, y_a)
          // |           /
          // |          .(x_p, y_p)
          // |         /
          // |        .(x_b, y_b) 
          // |       
          // |

          float x_p = (x_a + x_b) / 2;
          float y_p = (y_a + y_b) / 2;
          float angle = atan2f(y_b - y_a, x_b - x_a);
          float sine = sinf(angle);
          float cosine = cosf(angle);
          float a_sqrt = (x_a - x_p) * (x_a - x_p) + (y_a - y_p) * (y_a - y_p);

          float A = cosine * (x - x_p) + sine * (y - y_p); // what is A?
          float B = sine * (x - x_p) - cosine * (y - y_p); // what is B?

          float judge = A * A / a_sqrt + B * B / b_sqrt;
          }

**Comment by KeyKy** [comment]
Ho, i see. (cosine, sine) is a vector and [(x - x_p), (y - y_p)] is a vector. A is a projection.

**Comment by tsimk** [comment]
Correct. It follows the ellipse formulation quite closely:
https://en.wikipedia.org/wiki/Ellipse#General_ellipse
although it could be written more cleanly without the sines & cosines.
