### ISSUE TITLE
Virus? false positive? detected in the dataset 

### ISSUE THREAD

**Issue by salvador-blanco** [ZheC/Realtime_Multi-Person_Pose_Estimation#121]
So I ran the getData.sh file to get the COCO dataset, and I set my lab Network Attached Storage as the directory to download it.
In the middle of the download I receive a message from one of the administrators
![virus](https://user-images.githubusercontent.com/30084029/33134844-21c6febc-cfe4-11e7-9971-601c81d399a3.png)
COCO/coco/MatlabAPI/private/gasonMex.mexa64 

It freaked out the other lab members

Is it a false positive ?

**Comment by gineshidalgo99** [comment]
coco is an official API from Microsoft (now renamed as Cocoapi):
https://github.com/cocodataset/cocoapi

So it's definitively a false positive. Thanks

**Comment by salvador-blanco** [comment]
Thank you very much!!!
Now I can continue working
