### ISSUE TITLE
PAF preparation

### ISSUE THREAD

**Issue by coldgemini** [ZheC/Realtime_Multi-Person_Pose_Estimation#123]
Hi zhe,
where did you generate the PAF data? I didn't see any in the data preparation scripts. Is it somewhere in the main code?

thanks

**Comment by anatolix** [comment]
It prepared by Caffe layer approximately here https://github.com/CMU-Perceptual-Computing-Lab/caffe_train/blob/master/src/caffe/cpm_data_transformer.cpp
