### ISSUE TITLE
The function of "mapIdx" ?

### ISSUE THREAD

**Issue by USTClj** [ZheC/Realtime_Multi-Person_Pose_Estimation#134]
Hi, every one, who can kindly explain it to me? What's the meaning of  the value,  mapIdx?
Thank you !

**Comment by rewonderful** [comment]
兄弟，我也想知道这个是啥，咱俩加个微信讨论一下吧，壹伍陆肆伍零捌伍捌陆伍，求交流。我挨行注释掉之后，后面的limb就会变，可能是肢体的序列？可是前面的limbSeq已经表明序列了啊，愁

**Comment by nnop** [comment]
`mapIdx` is the index into `pafmap_avg` of the limb corresponding to `limbSeq`.
