### ISSUE TITLE
How to undersatand the criterion in demo.py？

### ISSUE THREAD

**Issue by USTClj** [ZheC/Realtime_Multi-Person_Pose_Estimation#135]
in demo.ipynb：

`score_midpts = np.multiply(vec_x, vec[0]) + np.multiply(vec_y, vec[1])
                
                score_with_dist_prior = sum(score_midpts)/len(score_midpts) \
                                        + min(0.5*oriImg.shape[0]/norm-1, 0)
                
                criterion1 = len(np.nonzero(score_midpts > param['thre2'])[0]) > 0.8 * len(score_midpts)
                # parm['thre2'] = 0.05
                criterion2 = score_with_dist_prior > 0
                if criterion1 and criterion2:
                    connection_candidate.append([i, j, score_with_dist_prior, 
                                                 score_with_dist_prior+candA[i][2]+candB[j][2]])`

How to understand the value of “min(0.5*oriImg.shape[0]/norm-1, 0)”？  The tow probability terms are added directly.  And how to understand the two criterion？？

**Comment by Ai-is-light** [comment]
I have the same problems. I want to re-train the smaller model about this excellent work, however, the output is the heat map. I have not any idea about testing the model I trained. Hope @ZheC can @ZheC give some ideas about how to test the model and get the AP values.Thanks @USTClj

**Comment by shengjunpan** [comment]
Is there any answer to this question? I would also like to know how this prior works. This ticket was closed without any explanations.
