### ISSUE TITLE
File 'model/_trained_COCO/pose_iter_440000.caffemodel' missing

### ISSUE THREAD

**Issue by AndreiCostinescu** [ZheC/Realtime_Multi-Person_Pose_Estimation#138]
Hi @ZheC 

Let me first thank you for your work and that you have uploaded the code here on GitHub!

I am trying to run the demo.ipynb file, but I get an error at the fourth cell.
I think that it tries to recreate the network from the "*.prototxt" and the "*.caffemodel" files. However, the file `caffemodel = '../../model/_trained_COCO/pose_iter_440000.caffemodel'` is missing from the current version of the repository.
Could you please either upload the `pose_iter_440000.caffemodel` file in the repository or send me a link to where I can download the file?

Thanks in advance!

Best regards,

Andrei

**Comment by stuartspotlight** [comment]
How was this resolved?

**Comment by haleqiu** [comment]
I met the same problem and wondering where I can get the pre-trained model. @AndreiCostinescu

**Comment by haleqiu** [comment]
Well, I found the model as following:
Run cd testing; get_model.sh to retrieve our latest MSCOCO model from our web server.
