### ISSUE TITLE
How to understand for the "center_map" in the prototxt? What's the meaning for the networks?

### ISSUE THREAD

**Issue by Ai-is-light** [ZheC/Realtime_Multi-Person_Pose_Estimation#143]
layer {
  name: "image"
  type: "Slice"
  bottom: "data"
  top: "image"
  top: "center_map"
  slice_param {
    slice_point: 3
    axis: 1
  }
}
layer {
  name: "silence2"
  type: "Silence"
  bottom: "center_map"
}

 @ZheC @shihenw Looking forward your attention, Thanks

**Comment by ZheC** [comment]
The center map is for the old experiments, and it is not used anymore. Ideally, I should change the code in the cpm_data_transformer.cpp so that it will not generate a center map as the 4th channel.
