### ISSUE TITLE
Error in configuration process, project files may be invalid!

### ISSUE THREAD

**Issue by JoseRubio15** [ZheC/Realtime_Multi-Person_Pose_Estimation#144]
Dear all,

I have a problem during the installation of Openpose. Either I do it with windows or Ubuntu, I get the same alert (see screenshot). I do not know how to solve it, please help!

![captura de pantalla de 2018-02-05 18-46-51](https://user-images.githubusercontent.com/36168153/35820095-fb471c3a-0aa4-11e8-926c-94a4acdd7690.png)

This is the code which is generated:

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Check for working C compiler: /usr/bin/cc
Check for working C compiler: /usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/c++
Check for working CXX compiler: /usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
GCC detected, adding compile flags
Building with CUDA
CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing:  CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) 
cuDNN not found
Could NOT find GFlags (missing:  GFLAGS_INCLUDE_DIR GFLAGS_LIBRARY) 
Could NOT find Glog (missing:  GLOG_INCLUDE_DIR GLOG_LIBRARY) 
CUDA not found.
ubuntu_version="$(lsb_release -r)"
sudo apt-get update && sudo apt-get install wget -y --no-install-recommends
if [[ $ubuntu_version == *"14."* ]]; then
  wget -c "https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1404-8-0-local-ga2_8.0.61-1_amd64-deb"
  sudo dpkg --install cuda-repo-ubuntu1404-8-0-local-ga2_8.0.61-1_amd64-deb
elif [[ $ubuntu_version == *"16."* ]]; then
  wget -c "https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb"
  sudo dpkg --install cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb
fi
sudo apt-get update
sudo apt-get install cuda

CMake Error at CMakeLists.txt:220 (message):
  Install CUDA using the above commands.

Configuring incomplete, errors occurred!
See also "/home/jose/openpose/build/CMakeFiles/CMakeOutput.log".

**Comment by gineshidalgo99** [comment]
This is not an issue of this repo.

Still, it's telling you the error, CUDA was not found.

Check the doc/installation.md to know how to install it.
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md
