### ISSUE TITLE
implementing in windows

### ISSUE THREAD

**Issue by xxxyyyzzzz** [ZheC/Realtime_Multi-Person_Pose_Estimation#146]
I have tried executing getANNO.m in windows environment. But the mex files for gason.cpp is created as MEXA64(i.e for linux environment). So I couldn't proceed.
Basically, the doubt is can this repo be replicated in windows environment?
I would appreciate for any suggestions..

**Comment by younger-diao** [comment]
Excuse me,have you trained it in windows?

**Comment by xxxyyyzzzz** [comment]
No I couldn't. I dropped that idea
