### ISSUE TITLE
Error Caffe when running notebook

### ISSUE THREAD

**Issue by Sugarbank** [ZheC/Realtime_Multi-Person_Pose_Estimation#15]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0c5a6adc2d4a> in <module>()
      4 import PIL.Image
      5 import math
----> 6 import caffe
      7 import time
      8 from config_reader import config_reader

ImportError: No module named caffe

**Comment by ZheC** [comment]
Maybe https://github.com/BVLC/caffe/issues/263 is helpful
