### ISSUE TITLE
 Hungarian algorithm for part association

### ISSUE THREAD

**Issue by pavanteja295** [ZheC/Realtime_Multi-Person_Pose_Estimation#150]
Hi,
I read in the paper  that Hungarian algorithm is used for association of limbs when multiple contenders exist for a limb but in the code normal greedy association is done by eliminating the chances of multiple associations

Explanation in the paper is different.Any insights?

**Comment by ZheC** [comment]
This link explains the merging process quite well: https://arvrjourney.com/human-pose-estimation-using-openpose-with-tensorflow-part-2-e78ab9104fc8

Hope it helps!
