### ISSUE TITLE
subset understanding

### ISSUE THREAD

**Issue by xxxyyyzzzz** [ZheC/Realtime_Multi-Person_Pose_Estimation#151]
can someone explain what is happening in subset calculation part?
Its confusing to understand for multiperson image.
I would appreciate some replies..
Thanks in advance

**Comment by ZheC** [comment]
This link explains the merging process quite well: https://arvrjourney.com/human-pose-estimation-using-openpose-with-tensorflow-part-2-e78ab9104fc8

Hope it helps!
