### ISSUE TITLE
Newly implemented OpenPose(pytorch)

### ISSUE THREAD

**Issue by youansheng** [ZheC/Realtime_Multi-Person_Pose_Estimation#153]
https://github.com/youansheng/pytorch-cv/tree/master/methods/pose

**Comment by ZheC** [comment]
That's great, I add the link to the README. Could you include some example command line to use your code in the github repo?

**Comment by ZheC** [comment]
Oh, I just saw it in https://github.com/youansheng/pytorch-cv. That's helpful!

**Comment by youansheng** [comment]
Thanks！
