### ISSUE TITLE
Is this possible to train this project to detect my own dataset's keypoints?

### ISSUE THREAD

**Issue by Metal-joker** [ZheC/Realtime_Multi-Person_Pose_Estimation#154]
How can I re-implement this project to detect my own dataset's key points like clothes key points?
Is there anything like dataset or annotation format that need attention?
Anything will be very helpful!

**Comment by cchamber** [comment]
You should start with the COCO api demo and look at what you information you need to save in the annotation .json files. For the annotations there are several online tools you can use https://en.wikipedia.org/wiki/List_of_manual_image_annotation_tools . I am using labelMe. 

From there you can generate .h5 input files. I am using a keras version of the code written by michal faber and anatolix. Anatolix has code that allows you to generate the .h5 input file from the .json annotation files. Once you have the input files in .h5, you should be able to train the model with your own data.

**Comment by Metal-joker** [comment]
Thanks and I already have the annotation file, but is there any way to train with my own data with this project? I didn't find it in README

**Comment by christian-lanius** [comment]
As far as I can tell, you can not use openpose to retrain the underlying neural network. You should be able to use https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation and the modified caffe version the authors used (https://github.com/CMU-Perceptual-Computing-Lab/caffe_train) to train the caffe model. After training you can use your weights to replace the weights openpose uses for the model, i.e. the iter files. 
Somebody who is more experienced on retraining openpose should swoop in and correct any mistakes in my understanding!

**Comment by Anitkrun** [comment]
> You should start with the COCO api demo and look at what you information you need to save in the annotation .json files.
Can someone please explain this a bit more? I understand that I should check a COCO json file and see what are the 'members' of the annotated sections in an annotation file. Still how would i need to annotate the image should i retrain using the code.

**Comment by BeauDoggie** [comment]
您好！，来信收到，尽快给您回复。
