### ISSUE TITLE
CPU modes

### ISSUE THREAD

**Issue by Sugarbank** [ZheC/Realtime_Multi-Person_Pose_Estimation#16]
Hi, which implementations have CPU support?

C++
Matlab 
or Python

Cheers:)

**Comment by ZheC** [comment]
Matlab and Python, set use_gpu = 0 in the matlab config file (https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/config.m) or python config file (https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/python/config)
