### ISSUE TITLE
low FPS

### ISSUE THREAD

**Issue by xxxyyyzzzz** [ZheC/Realtime_Multi-Person_Pose_Estimation#162]
Hi, 
FPS value is too less for me, because of the time taken for greedy part and other preprocessing works additional to net forwarding..
Is there any way improve or change something to improve FPS?
It would be grateful if I get some suggestions and replies.
Thanks in advance

**Comment by ZheC** [comment]
There are several ways to speed up. This link should be helpful: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/faq.md#speed-up-and-benchmark

I think reducing the input image size and using fewer stages in the model can speed up a lot.

**Comment by xxxyyyzzzz** [comment]
Thanks for the reply. will reducing stages cause very less accuracy. In your point of view, how many number of stages is optimal?
Waiting for your reply.

**Comment by ZheC** [comment]
3 stages or 4 stages can still have reasonable accuracy.

**Comment by xxxyyyzzzz** [comment]
Thanks so much. Can you share how did you evaluate for only 2000 images
instead of whole 40K validaiton images?
Thanks in advance

**Comment by albertchristianto** [comment]
Hi, 
I'm just curious. Is there any real-time demo in python? 
Or just C++ version that you have been released recently?
Because greedy part and other post-processing took a lot of time in python. 
Thank you very much,
Albert

**Comment by ZheC** [comment]
We do not provide any real-time demo in python. You may want to check this repo https://github.com/ildoonet/tf-pose-estimation
