### ISSUE TITLE
How to generate mask images for MPI dataset

### ISSUE THREAD

**Issue by CHANYUEPO** [ZheC/Realtime_Multi-Person_Pose_Estimation#166]
Hi, can you tell me how to generate mask images for MPI dataset, genLMDB.py need the mask images,but i can't find the script to do that.

**Comment by ZheC** [comment]
We used the SSD detector to obtain all person's bounding boxes, then checked if the person is annotated using code and finally generated the mask for unannotated persons. 

You can download the masks from http://posefs1.perception.cs.cmu.edu/Users/ZheCao/masks_for_mpii_pose.tgz

**Comment by CHANYUEPO** [comment]
Thank you very much!
