### ISSUE TITLE
How to optimize memory in evalMPI.m and evalCOCO.m

### ISSUE THREAD

**Issue by Andrew-huhong** [ZheC/Realtime_Multi-Person_Pose_Estimation#167]
Hi,
With using evalMPII.m and evalCOCO.m program,  I meet the problem "out of memory". And I change the scale parameter from param.scale_search = [0.5 1 1.5 2] to param.scale_search = [1]. However,it's also the out of memory(my GPU memory is 12GB,CPU memory is 47GB). Badly, I cannot run the eval program by useing CPU.
So I set cpu, when I use evalMPII.m picture number 103, the cpu memory cost 46.6GB. Next, it's also out of memory.
From what has been showed above, how to optimize memory in evalMPI.m and evalCOCO.m
Thank you a lot!!!

**Comment by ZheC** [comment]
Oh, one common reason for this large memory issue is that cudnn is not enabled when compiling caffe. Could you enable cudnn and test again?

**Comment by Andrew-huhong** [comment]
Thank you very much, I get it!
