### ISSUE TITLE
MPII evaluation about /testing/evalMPII.m

### ISSUE THREAD

**Issue by DongJT1996** [ZheC/Realtime_Multi-Person_Pose_Estimation#168]
Hi,
I want to evaluate the model on MPII dataset, so i try to use the evalMPII.m to do it.
But when i try to run it, i can't find 'annolist_test_multi.mat' and 'config2'
![image](https://user-images.githubusercontent.com/25705996/39195941-81011b86-4813-11e8-9d55-cffd4716d997.png)
And i find that the code use the original image as input as shown in the following, but the MPII dataset protocal says that evaluation is done on group not the whole image
![image](https://user-images.githubusercontent.com/25705996/39196149-feebf14c-4813-11e8-80cd-f7a8e26db14b.png)

why do you try to do that?

**Comment by ZheC** [comment]
We decide to first obtain the results for all the people in the image and then select the human poses that are inside the group: https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/evalMPII.m#L74-L83

**Comment by Aakriti05** [comment]
How to get annolist_test_multi.mat ?

Kindly help!
