### ISSUE TITLE
Failed cases

### ISSUE THREAD

**Issue by albertchristianto** [ZheC/Realtime_Multi-Person_Pose_Estimation#169]
Hi, 
Have you tried your COCO trained model to inference image like below ?
![000533914](https://user-images.githubusercontent.com/32095448/39398337-cbfba4ca-4b3e-11e8-953f-644650488932.jpg)
![007787006](https://user-images.githubusercontent.com/32095448/39398354-0deff8cc-4b3f-11e8-8995-25256a8b2169.jpg)
I have no idea why your model didn't output any human pose in that image. Or I need to fine tune the model. 
Thank you for your attention.

**Comment by gineshidalgo99** [comment]
People inside water and upside-down people are data that has not been given into the OpenPose training code. Your only change is to fine-tune it with those kind of samples.

For the upside-down people, you can also rotate the image 180deg when giving it to OpenPose  (there is a flag to rotate the image)
