### ISSUE TITLE
Pose estimate for single person with less than full body in picture

### ISSUE THREAD

**Issue by jiexunsee** [ZheC/Realtime_Multi-Person_Pose_Estimation#17]
Hi Dr Zhe,

I have tried your pose estimator and it works brilliantly for single and multiple people. However, if there is only one person in the picture and the picture does not contain his full body, I get an error which says:

File "demo.py", line 254, in <module>
    partAs = connection_all[k][:,0]
TypeError: list indices must be integers, not tuple

Any idea how to resolve this, or does the pose estimator only work for full body pictures?

Thanks a lot!

**Comment by shihenw** [comment]
@jiexunsee, that is a bug that popped out when there's a limb connecting two joints that are both non-existing. Now it should be fixed. If the issues goes on please share your test image so we can look into it.

**Comment by jiexunsee** [comment]
Hi Shihen, thanks for the reply, I'll check it out!

**Comment by jiexunsee** [comment]
It works, thanks a lot!
