### ISSUE TITLE
What parameters were used on MPII dataset?

### ISSUE THREAD

**Issue by yw155** [ZheC/Realtime_Multi-Person_Pose_Estimation#170]
Hi @ZheC, I use you provided 'MPI.json' file to extract 343 images as the validation set to test the accuracy of you provided MPII-iter146000 model. The network input size is set as 368. The scale search uses 3 scales, which are 0.7, 1 and 1.3. The obtained accuracy is only 50.4 and much lower than the accuracy mentioned in the paper (79.1). I am not sure if it is the reason of parameter setting. Could you tell me what parameters were used on MPII val set? Thanks.

**Comment by ZheC** [comment]
The parameters I used is in:
https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/config.m#L66-L85 

50.4 seems to be a quite low number, probably you should plot the prediction and GT pose to check if anything is obviously wrong.

**Comment by yw155** [comment]
Hi @ZheC, I use all the default parameters and model to generate the predictions on the val set. Below are the detected pose results.
/home/yw/cmu-pose/Realtime_Multi-CPM/testing/result/vis_70.png

**Comment by ZheC** [comment]
I am closing this issue because you are posting the issues in a new thread (https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/issues/172)
