### ISSUE TITLE
How to change the batch size

### ISSUE THREAD

**Issue by srijandas07** [ZheC/Realtime_Multi-Person_Pose_Estimation#18]
When I am trying to execute demo.ipynb, its getting out of memory (inspite of using GPU) [error == cudaSuccess (2 vs 0) out of memory]
So, I think i need to alter the batch size. How can I do it?

**Comment by ZheC** [comment]
We perform scale search in the code as in the following. You can change the scale parameters in line 16 of https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/python/config
For example, to use one scale, you can set scale_search = 1 

for m in range(len(multiplier)):
    scale = multiplier[m]
    imageToTest = cv.resize(oriImg, (0,0), fx=scale, fy=scale, interpolation=cv.INTER_CUBIC)
    imageToTest_padded, pad = util.padRightDownCorner(imageToTest, model['stride'], model['padValue'])
