### ISSUE TITLE
The LMDB channel of MPI is 5, but cpm_data_transformer need 6

### ISSUE THREAD

**Issue by mashiwei** [ZheC/Realtime_Multi-Person_Pose_Estimation#181]
Hi @ZheC, I use genLMDB.py && MPI.Json && masks_for_mpii_pose.tgz you provided to generate the MPI LMDB, and the channel is 5(I guess the MPI don't have mask_all). Then I use setLayers.py to generate the prototxt and shell file for training(since I didn't find the prototxt and shell file for MPI, I modified a few parameters in setLayers.py, np =43 && np_in_lmdb=16 && num_output=16, and generate the files for MPI training. But I'm not sure if that is correct). When I started training, it prompts me "cpm_data_transformer.cpp:386] Check failed: datum_channels == 6 (5 vs. 6)". 
And my questions are:
1.Is my method to generate the prototxt and shell file right? What should I do if it is not correct?
2.The channel is mismatch, is this a bug?
Thank you very much!

**Comment by yw155** [comment]
Hi @mashiwei, about the first question, I think there should be no problem. You can try to test it at training. About the channel mismatch, you can modify the file of "cpm_data_transformer.cpp" and add a check that if np == 56, datum_channels == 6, else, datum_channels == 5. Hope this is useful.

**Comment by mashiwei** [comment]
@yw155 Thank you for your reply! I will try what you say!

**Comment by mashiwei** [comment]
Hi @yw155 , I have modified the file of "cpm_data_transformer.cpp", and the channel problem is solved. But I meet another problem:
I0517 20:44:50.396066 32072 layer_factory.hpp:77] Creating layer conv1_1
I0517 20:44:50.396081 32072 net.cpp:100] Creating Layer conv1_1
I0517 20:44:50.396097 32072 net.cpp:434] conv1_1 <- image
I0517 20:44:50.396107 32072 net.cpp:408] conv1_1 -> conv1_1
*** Aborted at 1526561090 (unix time) try "date -d @1526561090" if you are using GNU date ***
PC: @     0x7f428afe754e cv::Mat::operator=()
*** SIGSEGV (@0xeeeeeeee) received by PID 32072 (TID 0x7f4215cbd700) from PID 18446744073423220462; stack trace: ***
    @     0x7f42864714b0 (unknown)
    @     0x7f428afe754e cv::Mat::operator=()
    @     0x7f4288efb9fb cv::MatOp_Initializer::makeExpr()
    @     0x7f4288efc7ba cv::Mat::zeros()
    @     0x7f428b00e3c4 caffe::CPMDataTransformer<>::Transform_nv()
    @     0x7f428b00fdd6 caffe::CPMDataTransformer<>::Transform_nv()
    @     0x7f428b0ea512 caffe::CPMDataLayer<>::load_batch()
    @     0x7f428b11418f caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f428b0146d5 caffe::InternalThread::entry()
    @     0x7f427d4395d5 (unknown)
    @     0x7f42854456ba start_thread
    @     0x7f428654341d clone
    @                0x0 (unknown)

I can't figure out what caused this problem, do you have any advice? Thank you very much!

**Comment by mashiwei** [comment]
Hi @yw155 , I modified the "cpm_data_transformer.cpp" and the channel problem is solved. But I meet another problem:
I0517 21:40:08.483582  8997 layer_factory.hpp:77] Creating layer weight_stage1_L1
I0517 21:40:08.483590  8997 net.cpp:100] Creating Layer weight_stage1_L1
I0517 21:40:08.483594  8997 net.cpp:434] weight_stage1_L1 <- conv5_5_CPM_L1_conv5_5_CPM_L1_0_split_0
I0517 21:40:08.483614  8997 net.cpp:434] weight_stage1_L1 <- vec_weight_vec_weight_0_split_1
I0517 21:40:08.483623  8997 net.cpp:408] weight_stage1_L1 -> weight_stage1_L1
F0517 21:40:08.483652  8997 eltwise_layer.cpp:34] Check failed: bottom[i]->shape() == bottom[0]->shape() 
*** Check failure stack trace: ***
    @     0x7f54764905cd  google::LogMessage::Fail()
    @     0x7f5476492433  google::LogMessage::SendToLog()
    @     0x7f547649015b  google::LogMessage::Flush()
    @     0x7f5476492e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f5476beb7cd  caffe::EltwiseLayer<>::Reshape()
    @     0x7f5476c42261  caffe::Net<>::Init()
    @     0x7f5476c43ae1  caffe::Net<>::Net()
    @     0x7f5476ca87ba  caffe::Solver<>::InitTrainNet()
    @     0x7f5476ca9b27  caffe::Solver<>::Init()
    @     0x7f5476ca9eca  caffe::Solver<>::Solver()
    @     0x7f5476c9e0c3  caffe::Creator_SGDSolver<>()
    @           0x40afb9  train()
    @           0x4077c8  main
    @     0x7f5474c26830  __libc_start_main
    @           0x408099  _start
    @              (nil)  (unknown)

I modified some parameters in pose_train_test.prototxt, the num_output for CPM_L1 is 28, and the num_output for CPM_L2 is 16. I guess there is something wrong in the vec_weight layer, as showed below:

layer {
  name: "vec_weight"
  type: "Slice"
  bottom: "label"
  top: "vec_weight"
  top: "heat_weight"
  top: "vec_temp"
  top: "heat_temp"
  slice_param {
    slice_point: 38
    slice_point: 44
    slice_point: 82
    axis: 1
  }
}
layer {
  name: "label_vec"
  type: "Eltwise"
  bottom: "vec_weight"
  bottom: "vec_temp"
  top: "label_vec"
  eltwise_param {
    operation: PROD
  }
}
layer {
  name: "label_heat"
  type: "Eltwise"
  bottom: "heat_weight"
  bottom: "heat_temp"
  top: "label_heat"
  eltwise_param {
    operation: PROD
  }
} 
layer {
  name: "image"
  type: "Slice"
  bottom: "data"
  top: "image"
  top: "center_map"
  slice_param {
    slice_point: 3
    axis: 1
  } 
} 
layer {
  name: "silence2"
  type: "Silence"
  bottom: "center_map"
} 


Do you have any suggestions? Thank you very much!

**Comment by yw155** [comment]
Hi @mashiwei, the slice point should be modified as 28, 44, 72. Thanks.

**Comment by mashiwei** [comment]
Thanks for your quick response @yw155 !! Training has begun!
Thanks!!!

**Comment by HaoRanLyu** [comment]
@mashiwei

**Comment by HaoRanLyu** [comment]
@mashiwei

**Comment by travisCxy** [comment]
Hello, @mashiwei ,could you tell me how to add the check in detail.And another question is the mpii dataset has 14 joints, but coco has 17, what modification should I do when train mpii datasets. Thank you very much
