### ISSUE TITLE
Detecting human pose for small size people

### ISSUE THREAD

**Issue by albertchristianto** [ZheC/Realtime_Multi-Person_Pose_Estimation#194]
Dear admin,
I have done some experiment by using your code. I tried to implement your code in Video Surveillance system (VIRAT dataset), but your model can't detect small size people. I have tried to finetuned your model with different parameter for scale, but I still haven't gotten any positive result. (the lowest parameter scale in CPMtransformer data is 0.001). Later, I found that you also ignored people with segmentation area lower than 32*32. I am a little bit curious, what is the reason behind this setting?
Thank you very much.
Best regards,
Albert

**Comment by pinkfloyd06** [comment]
Hi @albertchristianto ,

l'm interested in the answer too.

Thanks
