### ISSUE TITLE
VGG

### ISSUE THREAD

**Issue by tomercohen11** [ZheC/Realtime_Multi-Person_Pose_Estimation#204]
First of all, Great work! Thanks for sharing with us.
I wondered have you been testing this architecture with stronger backbones than vgg? For example resnets?

Thanks.

**Comment by ZheC** [comment]
No, we haven't tested with other architectures yet. Sorry for the late response!

**Comment by find1dream** [comment]
I've test many backbones like resnet, densenet, mobilenet. But I found that VGG19 is the best backbone for this architecture.
