### ISSUE TITLE
Can you share demo.py with body-25 keypoints

### ISSUE THREAD

**Issue by XuSen123** [ZheC/Realtime_Multi-Person_Pose_Estimation#206]
The demo.py script you shared is written for body-19 key points. Could you share demo.py with body-25 keypoints, especially the index for connection sequence and middle joints heatmap correpondence

**Comment by Hzzone** [comment]
@XuSen123 
I think you just modify the limb sequence according [keypoints_pose_25.png](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/media/keypoints_pose_25.png).

**Comment by Asmox** [comment]
How about changing the model?

**Comment by gineshidalgo99** [comment]
You can also check the repo released last night:
https://github.com/CMU-Perceptual-Computing-Lab/openpose_train
