### ISSUE TITLE
when testing，the problem of line integral

### ISSUE THREAD

**Issue by Sierkinhane** [ZheC/Realtime_Multi-Person_Pose_Estimation#208]
can somebody tell me the meaning of line integral over the corresponding PAF? I can't understand it clearly

**Comment by ZheC** [comment]
This blog is written in a clear way that helps people understand the method: https://arvrjourney.com/human-pose-estimation-using-openpose-with-tensorflow-part-2-e78ab9104fc8, hope it helps!
