### ISSUE TITLE
How to train hands keypoint detection?

### ISSUE THREAD

**Issue by jinfagang** [ZheC/Realtime_Multi-Person_Pose_Estimation#219]
Does there any way to train hands keypoint using this repo? openpose provides only test scripts

**Comment by huntkao** [comment]
Well, the same question. 
Does anyone have idea or hint how to do the hand keypoints training?
Thanks.

**Comment by jinfagang** [comment]
@huntkao No mention train on hands, I can not even train on coco person keypoints....... It mess matlab with python which is really ugly and totally can not understand how they prepared dataset to train.

**Comment by huntkao** [comment]
I successfully trained on COCO person key points. Some code modifications are needed to reproduce the results. However the procedure for HAND key points is still unclear.
