### ISSUE TITLE
no display windows

### ISSUE THREAD

**Issue by simon199250** [ZheC/Realtime_Multi-Person_Pose_Estimation#22]
[platform] Ubuntu 14.04 +cuda7.5+cudnn4.0+opencv2.4.9
After make all,when I run the command of "./build/examples/rtpose/rtpose.bin",it appear a error about threads, which is: Finish spawning 1 threads. now waiting.
init done
opengl support available，
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections

However,then it all always waiting,no results,

when I run the command of “./build/examples/rtpose/rtpose.bin --video video/4.mp4  --logtostderr
I0223 18:30:11.356386  4326 rtpose.cpp:1687] Display resolution: 1280x720
I0223 18:30:11.356426  4326 rtpose.cpp:1693] Net resolution: 656x368
I0223 18:30:11.356444  4326 rtpose.cpp:1468] Finish spawning 1 threads.
I0223 18:30:11.356467  4329 rtpose.cpp:175] Setting GPU 0
init done 
opengl support available 
I0223 18:30:11.903545  4329 rtpose.cpp:180] GPU 0: copying to person net
I0223 18:30:13.752050  4329 rtpose.cpp:202] start_scale = 1
I0223 18:30:13.752099  4329 rtpose.cpp:231] Dry running...
I0223 18:30:13.972661  4329 rtpose.cpp:233] Success.
I0223 18:30:13.973018  4329 rtpose.cpp:1081] GPU 0 is ready
QMetaMethod::invoke: Unable to invoke methods with return values in queued connections
OpenCV Error: Assertion failed (src.cols > 0 && src.rows > 0) in warpAffine, file /home/dl/opencv-2.4.9/modules/imgproc/src/imgwarp.cpp, line 3455
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/dl/opencv-2.4.9/modules/imgproc/src/imgwarp.cpp:3455: error: (-215) src.cols > 0 && src.rows > 0 in function warpAffine

已放弃 (核心已转储).
could anyone help me solver the problem.Thank you!

**Comment by caowei2688** [comment]
I would like to ask what version of the CUDA,cudnn and opencv

**Comment by gineshidalgo99** [comment]
Please, could you try a non-OpenGL OpenCV version? We think the problem might be there.
If you are able to try it, please let us know if it works in that way! Thanks!

**Comment by caowei2688** [comment]
No way。 Still same，Do you need to use QT？could anyone help me solver the problem.Thank you!

**Comment by caowei2688** [comment]
install opencv 2.4.9 use  cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_TBB=ON -D BUILD_NEW_PYTHON_SUPPORT=ON -D WITH_V4L=ON -D INSTALL_C_EXAMPLES=ON -D INSTALL_PYTHON_EXAMPLES=ON -D BUILD_EXAMPLES=ON -D WITH_QT=ON -D WITH_OPENGL=OFF -D CUDA_ARCH_BIN=5.2 .. 
 right?

**Comment by simon199250** [comment]
dl@dl:~/Realtime_Multi-Person_Pose_Estimation-master/caffe_demo$ ./build/examples/rtpose/rtpose.bin --video video/4.mp4 --logtostder
ERROR: unknown command line flag 'logtostder'
dl@dl:~/Realtime_Multi-Person_Pose_Estimation-master/caffe_demo$ ./build/examples/rtpose/rtpose.bin --video video/4.mp4 --logtostderr
I0224 17:00:15.388440 14081 rtpose.cpp:1687] Display resolution: 1280x720
I0224 17:00:15.388492 14081 rtpose.cpp:1693] Net resolution: 656x368
I0224 17:00:15.388520 14081 rtpose.cpp:1468] Finish spawning 1 threads.
I0224 17:00:15.388542 14084 rtpose.cpp:175] Setting GPU 0
init done 
I0224 17:00:15.962482 14084 rtpose.cpp:180] GPU 0: copying to person net
I0224 17:00:17.780849 14084 rtpose.cpp:202] start_scale = 1
I0224 17:00:17.780913 14084 rtpose.cpp:231] Dry running...
I0224 17:00:18.013065 14084 rtpose.cpp:233] Success.
I0224 17:00:18.013418 14084 rtpose.cpp:1081] GPU 0 is ready
OpenCV Error: Assertion failed (src.cols > 0 && src.rows > 0) in warpAffine, file /home/dl/Caffe/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/imgproc/src/imgwarp.cpp, line 5573
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/dl/Caffe/Install-OpenCV-master/Ubuntu/3.0/OpenCV/opencv-3.0.0/modules/imgproc/src/imgwarp.cpp:5573: error: (-215) src.cols > 0 && src.rows > 0 in function warpAffine

已放弃 (核心已转储)
dl@dl:~/Realtime_Multi-Person_Pose_Estimation-master/caffe_demo$ 

use opencv2.4.9 and opencv3.0.0    

The same problem, please help solve this problem, thank you

**Comment by ZheC** [comment]
It seems that the video frames cannot be extracted properly, thus it has the error: (-215) src.cols > 0 && src.rows > 0 in function warpAffine. I would suggest (1) check the path to the video is correct (2) check whether you can visualize the frame by imshow()
