### ISSUE TITLE
training of images with no humans

### ISSUE THREAD

**Issue by Aakriti05** [ZheC/Realtime_Multi-Person_Pose_Estimation#228]
I have realized that the training does not include images that have no humans in the COCO dataset. 
genJSON.m does not include the images which have no key-points and discards them.
Isn't it wrong to do that? The model will not learn where to not predict human.  
Can someone throw light on this issue?

**Comment by oujieww** [comment]
@Aakriti05 i think it is ok. There may not be image without human or kpts,but this is not same as object detection. there are human areas and background area in images, heatmap must to predict background area with very low signal~~~~, this is just like negative image
