### ISSUE TITLE
Unable to find  joints plot code 

### ISSUE THREAD

**Issue by wzmsltw** [ZheC/Realtime_Multi-Person_Pose_Estimation#23]
Hi ZheC
Thanks for making your code available in Github, your model performs so great!
I have a problem that I cannot find joints drawing code  anywhere. I want to change the form of display result in image, such as color and line width. How can I find these code?
Thanks

**Comment by ZheC** [comment]
Which code do you mean, Matlab, C++ or Python?

**Comment by wzmsltw** [comment]
C++

**Comment by ZheC** [comment]
It is in the function __global__ void render_pose_coco_parts of https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/blob/master/src/rtpose/renderFunctions.cu , from line 394

**Comment by wzmsltw** [comment]
Thanks!
I thought you will use OpenCV functions to plot joints so I failed to find it.
