### ISSUE TITLE
About PAFs

### ISSUE THREAD

**Issue by NIEYALI** [ZheC/Realtime_Multi-Person_Pose_Estimation#24]
@ZheC  Thanks for your great work. But when I read the paper, I have some confused about 'Part Affinity Fields for Part Association' this part. I want to check the part of codes, could you tell me where can I find it. Thanks a lot.

**Comment by ZheC** [comment]
Do you mean the code for generating PAF in training? It is in line 1082~1134 of https://github.com/CMU-Perceptual-Computing-Lab/caffe_train/blob/master/src/caffe/cpm_data_transformer.cpp

**Comment by NIEYALI** [comment]
Thanks a lot
