### ISSUE TITLE
Input Imagedata normalization problem

### ISSUE THREAD

**Issue by zhangmGoL** [ZheC/Realtime_Multi-Person_Pose_Estimation#27]
@ZheC 
Thanks for your great work. I have read your paper and your demo-code, and was confused by the normalization method you have done to the input image-data during test and train. In test-mode, in the frame-generation thread, the pixel value is normalized by p(i,j)=(p(i,j)-0.5)/256, while in train-mode, the image-data is normalized by p(i,j)=(p(i,j)-128)/256, I want to know if it makes sense to the network performance and why it's different in two modes. Additionally, what range of input is needed for VGG19, (-0.5,+0.5) or (0,1), which type will be better? Thanks in advance!

**Comment by ZheC** [comment]
Could you point me where is p(i,j)=(p(i,j)-0.5)/256? I could not find them now. Thanks

**Comment by zhangmGoL** [comment]
I'm sorry... I was wrong that you do it right by p = p/256 - 0.5, in method of 'process_and_pad_image', Thank you!

**Comment by xiaoyong** [comment]
The VGG19 model was trained with a different normalization way, i.e. with mean subtraction only, no scaling. See [https://gist.github.com/ksimonyan/3785162f95cd2d5fee77](url). Could this inconsistence cause any trouble when fine-tuning?

**Comment by jiangwqcooler** [comment]
@ZheC I have the same problem of normalization, (-0.5, +0.5) or (0, 1) which better?
code: net.blobs['data'].data[...] = np.transpose(np.float32(imageToTest_padded[:,:,:,np.newaxis]), (3,2,0,1))/256 - 0.5

**Comment by USTClj** [comment]
It also doubts me.
