### ISSUE TITLE
Benchmark of the train project

### ISSUE THREAD

**Issue by zhangmGoL** [ZheC/Realtime_Multi-Person_Pose_Estimation#28]
@ZheC 
I found that in your train project, the solver has not defined a test net yet, so how to check the performance of the network on the validation-set, maybe some evaluate-methods should be given for testing. I would be appreciated if you could open source the evaluation code of your work on the COCO and MPI datasets, as you reported in the paper. Thanks a lot!!

**Comment by priyapaul** [comment]
So, what about the matlab evalCOCO.m  evalMPII  for evaluation?

**Comment by ZheC** [comment]
Yes, the code is https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/evalCOCO.m and https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/evalMPII.m
