### ISSUE TITLE
A confused question in the data_transformer.cpp

### ISSUE THREAD

**Issue by crsailing** [ZheC/Realtime_Multi-Person_Pose_Estimation#3]
I have read your paper, but I have a question when I check the training source code (caffe_train).
In "generateLabelMap()", line between 1840 and 1856, it seems 'count' used in 'putVecMaps()'  always is zero-Mat.

**Comment by ZheC** [comment]
The count is used for cross-over situation, e.g., if two left legs overlapping with each other, then in the overlapping area, each pixel will have two direction vectors (from the two legs)
