### ISSUE TITLE
Possibility of this algorithm in mobile devices

### ISSUE THREAD

**Issue by dswwfg** [ZheC/Realtime_Multi-Person_Pose_Estimation#30]
thank you for your algorithm. I used this algorithm on Ubuntu. and I want to ask you about the possibility of this algorithm in mobile devices like android.

**Comment by gineshidalgo99** [comment]
We are using Caffe and OpenCV. If you are able to install Caffe and OpenCV on a mobile, ideally our code should just be a C++ extension of those 2 libraries.

We are interested in knowing if you are able to work on mobile devices with out algorithm. We might quite probably support mobile devices if the algorithm can runs there.
