### ISSUE TITLE
Evaluation in Matlab

### ISSUE THREAD

**Issue by crsailing** [ZheC/Realtime_Multi-Person_Pose_Estimation#37]
Hi ZheC,
I have some questions about evaluation code in Matlab.
What is the type of `coco_val` in `testing/eval.m` line 12, or how can we get `coco_val`?
In addition, if  the number of CPM stage is set as 6, `twoLevel`  needs to changes to 7, is it right?

Thanks!

**Comment by ZheC** [comment]
coco_val is just an array which stores all the image index for your validation set. It should be straightforward to generate the array. twoLevel indicates whether the network is two branch or not, so it should be set as 1.

**Comment by priyapaul** [comment]
@crsailing  were you able to figure out how to use evaluation? Could you please help me with that?
@ZheC I  dont know, array of image index, mean arrray of image names?  and what does this do? 
`
oriImg = imread('....',names_cell{:,i})`

**Comment by crsailing** [comment]
@priyapaul you need to modify the code to load pictures. I used the file `image_info_val2014_1k.txt` in caffe_rtpose to evaluate the model.

**Comment by priyapaul** [comment]
@crsailing  Thank you very much ! So you mean, you used image_info_val2014_1k.txt in the matlab evalCOCO.m?
Would you mind explaining a bit more?  what should I have in coco_val and where should  I use  image_info_val2014_1k.txt ?

**Comment by louielu1027** [comment]
@crsailing  If I use the file image_info_val2014_1k.txt ,how to change the code?  Thank you!
