### ISSUE TITLE
evaluation issue

### ISSUE THREAD

**Issue by venus024** [ZheC/Realtime_Multi-Person_Pose_Estimation#38]
Hi, ZheC
We met problems when running the following codes. 
`"for part = 1:12
            index = subset(ridxPred,part);
            if(index >0)
                part_cnt = part_cnt +1;
                point(part_cnt).x = candidates(index,1);
                point(part_cnt).y = candidates(index,2);
                point(part_cnt).score = candidates(index,3);
                point(part_cnt).id = orderMPI(part);
                score_sum = score_sum + candidates(index,3);
            end
        end`

1. Undefined function 'orderMPI' for input arguments of type 'double'.
2. should the first line of the code paragraph be "for part = 1:12" or "for part = 1:17" when evaluated on MS COCO?

Thanks!

Best Regards!

Venus

**Comment by ZheC** [comment]
You are right, I corrected those issues in this commit: https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/commit/177e2d9cc5418c6c1807651e18a3a8e7b9e3a48e

Please let me know if you meet any other issue.
