### ISSUE TITLE
Extract bounding box as well of the person out of the code 

### ISSUE THREAD

**Issue by hasanirtiza** [ZheC/Realtime_Multi-Person_Pose_Estimation#4]
I am using your Matlab demo. I skimmed through the code and It appeared to me that the code in its given form does not output bounding box of a person. I understand one could compose the box out of key points but I was wondering if it is possible through the original code to get the bounding box of a person as well ?  

Regards

**Comment by ZheC** [comment]
We didn't try that before but it will be easy to implement. You can modify the following code to do that after running '[candidates, subset] = connect56LineVec(oriImg, final_score, param, vis);'. It has two for loops to go over each person subset and each part/joint of that person. 

for ridxPred = 1:size(subset,1)
    for part = 1:14
        index = subset(ridxPred,part);
        if(index >0)
            part_cnt = part_cnt +1;
            x = candidates(index,1);
            y = candidates(index,2);
            
            % update max_x, min_y
            % update max_y, min_y
        end
    end
end
