### ISSUE TITLE
Undefined symbol in libcaffe.so.1.0.0-rc3

### ISSUE THREAD

**Issue by mddrill** [ZheC/Realtime_Multi-Person_Pose_Estimation#40]
Hi, this is some impressive software you guys have. I'm trying to follow the instructions for training in the README, but I'm stuck on this one issue and I cannot find a solution. When I run genLMDB.py I get this error:

```
Traceback (most recent call last):
  File "training/setLayers.py", line 15, in <module>
    import caffe
  File "/home/mrmagic/caffe_rtpose/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/mrmagic/caffe_rtpose/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: /home/mrmagic/caffe_rtpose/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE
```

Does anyone know what this means or how to fix this? I have no idea what to do. I made sure to run `make pycaffe` in caffe_train and set my PYTHONPATH to /path/to/python/caffe. I've also tried this same process with caffe_rtpose instead of caffe_train.

Any help would be greatly appreciated.

**Comment by ZheC** [comment]
It seems that when you run setLayers.py, it adds the caffepath of caffe_rtpose instead of caffe_train. Do you set the path correctly in line 12 of https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/setLayers.py

**Comment by mddrill** [comment]
Thank you for responding, I changed both genLMDB.py and setLayers.py so that the path says sys.path.insert(0, os.path.join('/path/to/caffe_train/', 'python/'))

But I'm still getting the same error, any ideas?

**Comment by ZheC** [comment]
From the error you posted (ImportError: /home/mrmagic/caffe_rtpose/python/caffe/../../build/lib/libcaffe.so.1.0.0-rc3: undefined symbol: _ZN2cv7imwriteERKNS_6StringERKNS_11_InputArrayERKSt6vectorIiSaIiEE), I believe it is related to pycaffe path issue. But I do not know why it still occurs after you setting the path in the code.

**Comment by mddrill** [comment]
I uninstalled Opencv 3.2 and installed OpenCV 2.4 and did a make clean, and that solved the issue.
