### ISSUE TITLE
Error running train_pose.sh

### ISSUE THREAD

**Issue by mddrill** [ZheC/Realtime_Multi-Person_Pose_Estimation#42]
Hi, I'm getting much closer to being able to train a network with this. I just have this one error when I run train_pose.sh:

```
I0328 19:23:52.507542 17876 cpm_data_transformer.cpp:242] CPMDataTransformer constructor done.
I0328 19:23:52.508219 17884 db_lmdb.cpp:35] Opened lmdb /home/mrmagic/COCO_kpt/lmdb_trainVal
*** Aborted at 1490743432 (unix time) try "date -d @1490743432" if you are using GNU date ***
PC: @     0x7fc73809bdbf (unknown)
*** SIGBUS (@0x7ede92c5600a) received by PID 17876 (TID 0x7fc712888700) from PID 18446744071876993034; stack trace: ***
    @     0x7fc73f6134b0 (unknown)
    @     0x7fc73809bdbf (unknown)
    @     0x7fc73809c0c8 (unknown)
    @     0x7fc73809c3ac (unknown)
    @     0x7fc73809b173 mdb_cursor_get
    @     0x7fc740e932d5 caffe::db::LMDB::NewCursor()
    @     0x7fc740e6900f caffe::DataReader::Body::InternalThreadEntry()
    @     0x7fc740e58935 caffe::InternalThread::entry()
    @     0x7fc736d2f5d5 (unknown)
    @     0x7fc73135d6ba start_thread
    @     0x7fc73f6e482d clone
```

I've never seen an error like this before, so if someone could point me in the right direction as to how to debug it that would be amazing!

I'm not sure if this is relevant or not, but when I run `make runtest` in `caffe_train` after running `make all; make test` I get this:

```
F0328 20:40:02.593730 32048 pooling_layer.cu:212] Check failed: error == cudaSuccess (10 vs. 0)  invalid device ordinal
*** Check failure stack trace: ***
    @     0x7fa3f7f2226d  google::LogMessage::Fail()
    @     0x7fa3f7f24083  google::LogMessage::SendToLog()
    @     0x7fa3f7f21dfb  google::LogMessage::Flush()
    @     0x7fa3f7f24a6e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa3f56977c1  caffe::PoolingLayer<>::Forward_gpu()
    @           0x4798a6  caffe::Layer<>::Forward()
    @           0x482d7d  caffe::MaxPoolingDropoutTest_TestForward_Test<>::TestBody()
    @           0x91a693  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @           0x913caa  testing::Test::Run()
    @           0x913df8  testing::TestInfo::Run()
    @           0x913ed5  testing::TestCase::Run()
    @           0x9151af  testing::internal::UnitTestImpl::RunAllTests()
    @           0x9154d3  testing::UnitTest::Run()
    @           0x46dd6d  main
    @     0x7fa3f47f6830  __libc_start_main
    @           0x4757d9  _start
Makefile:523: recipe for target 'runtest' failed
make: *** [runtest] Aborted (core dumped)
```
This doesn't happen when I run the same command with regular caffe, which makes me think this 
is a caffe_train issue, not a caffe issue. 

Any help at all would be greatly appreciated,
Thanks!

**Comment by mddrill** [comment]
I think the problem was that I was using CUDA 8.0, I had to add 
```
-gencode arch=compute_52,code=sm_52 \
-gencode arch=compute_60,code=sm_60 \
-gencode arch=compute_61,code=sm_61 \
-gencode arch=compute_61,code=compute_61
```
To CUDA_ARCH in Makefile.config after that I ran into a file not found error and had to change the bottom level directory in `dataFolder` and source to `lmdb` instead of `lmdb_trainVal` so that it could find the .mdb files

Just figured I would post that in case anyone else ran into the same problem

**Comment by wujiyoung** [comment]
@mddrill I am getting the same problem, I use the CUDA_ARCH you added above, and I am sure that the source is pointed to correct lmdb directory in pose_train_test.prototxt. But the problem still exists.
Any further idea about the problem?
Thank you!

**Comment by Minotaur-CN** [comment]
I bave error when training the lmdb ,when training 1900 iteration.
Any one solve this problem before? 
Thanks in advance!

Regards!

=================================================================
I1016 10:34:47.675484 11884 sgd_solver.cpp:106] Iteration 1900, lr = 4e-05
F1016 10:36:11.466152 11892 cpm_data_transformer.cpp:386] Check failed: datum_channels == 6 (0 vs. 6) 
*** Check failure stack trace: ***
    @     0x7f3ae04f45cd  google::LogMessage::Fail()
    @     0x7f3ae04f6433  google::LogMessage::SendToLog()
    @     0x7f3ae04f415b  google::LogMessage::Flush()
    @     0x7f3ae04f6e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f3ae0d07e1b  caffe::CPMDataTransformer<>::Transform_nv()
    @     0x7f3ae0b720f5  caffe::CPMDataLayer<>::load_batch()
    @     0x7f3ae0b837af  caffe::BasePrefetchingDataLayer<>::InternalThreadEntry()
    @     0x7f3ae0b37d05  caffe::InternalThread::entry()
    @     0x7f3ad673a5d5  (unknown)
    @     0x7f3ad0d796ba  start_thread
    @     0x7f3aded713dd  clone
    @              (nil)  (unknown)

**Comment by oujieww** [comment]
maybe that one of dataset is wrong.I thank u can delete that image of the dataset
