### ISSUE TITLE
Has anyone successfully installed caffe_train and train this model?

### ISSUE THREAD

**Issue by yxchng** [ZheC/Realtime_Multi-Person_Pose_Estimation#44]
My specs is ubuntu 16.04, titan x pascal, opencv 2.4.13, cuda 8, but I am not able to install caffe_train nor use setLayer.py.

My caffe_train gives error when running runtest and running python setLayer.py gives
'''
Traceback (most recent call last):
  File "setLayers.py", line 17, in <module>
    import caffe
  File "/home/yxchng/caffe_train/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/yxchng/caffe_train/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory
'''

**Comment by ZheC** [comment]
Based on your error, it seems that cuda lib is not in your system path. One thing you may try is

vi ~/.bashrc
[add the following in the bottom of the file]
export PATH=/usr/local/cuda-8.0/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/cuda-8.0/lib64:$LD_LIBRARY_PATH

vi /etc/ld.so.conf
[add the following in the bottom of the file]
/usr/local/cuda-8.0/lib64
sudo ldconfig

**Comment by yxchng** [comment]
Thanks. Can I know if the file in example_proto the original setting that is used to train the model? I see 600,000 iterations. Did you let the model train for so long? Can I know roughly how long did you train the model?

**Comment by ZheC** [comment]
Our best model is in iteration 440,000. It achieves similar performance around iteration 330,000, which takes almost one week with two gpus. I suggest fine-tuning our model to save training time.

**Comment by moin59** [comment]
Hi, I got this error. I have changed the cuda directory in .config file. I can't find out the solution

[  1%] Building NVCC (Device) object src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_nesterov_solver.cu.o
/home/wh/caffe_train/include/caffe/util/cudnn.hpp(112): error: too few arguments in function call

1 error detected in the compilation of "/tmp/tmpxft_000031e8_00000000-5_nesterov_solver.cpp4.ii".
CMake Error at cuda_compile_generated_nesterov_solver.cu.o.cmake:266 (message):
  Error generating file
  /home/wh/caffe_train/build/src/caffe/CMakeFiles/cuda_compile.dir/solvers/./cuda_compile_generated_nesterov_solver.cu.o


src/caffe/CMakeFiles/caffe.dir/build.make:493: recipe for target 'src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_nesterov_solver.cu.o' failed
make[2]: *** [src/caffe/CMakeFiles/cuda_compile.dir/solvers/cuda_compile_generated_nesterov_solver.cu.o] Error 1
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
