### ISSUE TITLE
Matlab demo : Check failed: error == cudaSuccess  (2 vs. 0)  out of memory 

### ISSUE THREAD

**Issue by priyapaul** [ZheC/Realtime_Multi-Person_Pose_Estimation#45]
I am running matlab code for demo. But I get this error. Where is the scale_search param in matlab code, as mentioned in an issue of python demo?

**Comment by ZheC** [comment]
scale parameter is in line 48 in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/config.m

**Comment by priyapaul** [comment]
Even after changing the scale_search =1 , I am getting the same out of memory error.The c++ demo codes works for me. Bu I need matlab for evaluation: Is there anything else I can do about it?

**Comment by wiku30** [comment]
How to scale the parameter and what is the effect? The comments do not show these.

**Comment by fmnoori** [comment]
Hi, Apologize for posting here too. 
I am getting this error. can anyone please guide me what to do next?

https://github.com/CMU-Perceptual-Computing-Lab/caffe_rtpose/issues/44#issuecomment-417434196
