### ISSUE TITLE
Retraining: Freeze heat map weights

### ISSUE THREAD

**Issue by priyapaul** [ZheC/Realtime_Multi-Person_Pose_Estimation#46]
I would want to fix the weights for predicting heat map and retrain using a different data set. Is it just enough to put param{ lr_mult=0} for all 6 stages of 'L2' convolution layers?

**Comment by priyapaul** [comment]
@ZheC Could you please have a look at this?

**Comment by ZheC** [comment]
Sorry for the late response. Yes, all heatmap related convolution layer's name ends with '_L2'. You can set lr_mult = 0 to freeze their weights.
