### ISSUE TITLE
coco_val , imread -Matlab evaluation 

### ISSUE THREAD

**Issue by priyapaul** [ZheC/Realtime_Multi-Person_Pose_Estimation#49]
@ZheC I am sorry, I went through different issues on this, but could not figure it out!

I don't know, if array of image index, mean array of image names? and what does the following  do?
oriImg = imread('....',coco_val(i)) are we supposed to edit something here? 
Could you briefly explain how to use your evaluation code? It is not being called from demo, so how should I run this code. How did you generate coco_val? Would you be kind enough to explain briefly!

**Comment by yaobaic** [comment]
@priyapaul  Could you explain briefly how you did it? Thank you!!
