### ISSUE TITLE
Using on Windows OS

### ISSUE THREAD

**Issue by Prakash19921206** [ZheC/Realtime_Multi-Person_Pose_Estimation#5]
Hi
after installing CUDA & downloading cudnn binaries, i used Cygwin64 Terminal on windows and entered 
          `$ ./install_caffe_and_cpm.sh`
got the following output
```

------------------------- INSTALLING CAFFE AND CPM -------------------------
NOTE: This script assumes that CUDA and cuDNN are already installed on your mach
------------------------- Checking Ubuntu Version -------------------------
./install_caffe_and_cpm.sh: line 23: lsb_release: command not found
Ubuntu
Ubuntu release older than version 14. This installation script might fail.
------------------------- Ubuntu Version Checked -------------------------

------------------------- Checking Number of Processors ------------------------
4 cores
------------------------- Number of Processors Checked -------------------------

------------------------- Installing some Caffe Dependencies -------------------
./install_caffe_and_cpm.sh: line 50: sudo: command not found
./install_caffe_and_cpm.sh: line 51: sudo: command not found
./install_caffe_and_cpm.sh: line 53: sudo: command not found
./install_caffe_and_cpm.sh: line 54: sudo: command not found
./install_caffe_and_cpm.sh: line 57: sudo: command not found

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed
------------------------- -------------------------
```
any workaround or changes in code to try on windows?
Thanks & Regards

**Comment by gineshidalgo99** [comment]
I guess you could try to edit the script and remove the `sudo` command, or you can install manually the software the script is installing (the script is plan bash code so it can be easily read) as well as manually compiling the library (again, you might check the script to see the specific `make` commands).

**Comment by Prakash19921206** [comment]
@gineshidalgo99, Thanks for your reply.
 i changed script. removed `sudo `& replaced `apt-cyg `with `apt-cyg`.
i think below error is because the libraries are for ubuntu/linux
`Unable to locate package libprotobuf-dev` 
i think i'll have to use minGW to get .dll for `libprotobuf-dev libleveldb-dev libsnappy-dev libhdf5-serial-dev`
i'll keep trying, if i succeed then definitely i'll share procedure.

**Comment by hinmanj** [comment]
I have it working on Windows 10 with Python 2.7 (for windows) installed.

Just build caffe from source, as it's compatible with windows now, and set up all your paths and install all the proper dependencies (I used pip in Powershell), and things should work out of the box.

I almost had it working in Python 3.5 but after having to change a couple things in demo.ipynb and with it still not working, I gave up and just decided to swap for Python 2.7. Note that I'm also not a python programmer.

**Comment by Prakash19921206** [comment]
@hinmanj, i'm having many errors in cmake(boost & Caffe)
can you make a brief documentation?

**Comment by raymondsa** [comment]
@hinmanj @ZheC 
Hello dear ,  I have run the demo in windows, GTX1080  and  Matlab2015a without any problems.
The problem is that the running time is too slow ,  the program can process ~10-15 frames in 1 minute.

**Comment by gineshidalgo99** [comment]
It makes sense. You might use the new C++ library in order to speed up to ~8 fps in the GTX1080:
https://github.com/CMU-Perceptual-Computing-Lab/openpose
