### ISSUE TITLE
Crash of python example

### ISSUE THREAD

**Issue by ZdenekM** [ZheC/Realtime_Multi-Person_Pose_Estimation#50]
On 64bit Ubuntu 14.04 with CPU-only caffe (changed use_gpu in config file to 0) I'm getting this:

```
F0421 13:25:27.432996 22411 syncedmem.hpp:33] Check failed: *ptr host allocation of size 53086208 failed
*** Check failure stack trace: ***
```

Any idea what might be wrong? Many thanks in advance.

**Comment by gineshidalgo99** [comment]
We use GPU, we do not support CPU mode so far because our initial results for CPU were below 1 fps.

**Comment by ZdenekM** [comment]
I tried on two different machines and it runs fine there - just bit slow. I'm now experimenting with openCL caffe.
