### ISSUE TITLE
python version cost 1.5s every image

### ISSUE THREAD

**Issue by liaowang0125** [ZheC/Realtime_Multi-Person_Pose_Estimation#59]
image size:1920*1080
I detetct pose using python version,and only want to get all_peaks,it cost average 1.5s per image,and I use GPU too, why so slow?

**Comment by ZheC** [comment]
Change the scale search parameter in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/testing/python/config#L16

Use scale_search = 1 is usually enough

**Comment by liaowang0125** [comment]
thank you!
