### ISSUE TITLE
augmentation difficult to understand

### ISSUE THREAD

**Issue by mdering** [ZheC/Realtime_Multi-Person_Pose_Estimation#60]
I'm trying to reimplement the basics of what you've done in python and I'm having a really hard time figuring out what your training code does. I understand the basics, it seems to center on a person, zoom, include other people, unless they're too far away, flip, rotate, a few other things, and then I'm training on a model which is basically identical to yours. The problem is the heatmaps end up looking pretty sparse, or even collapsing to 0 and nothing is found. Could you give a general breakdown of what happens and when, specifically when generating target data and augmenting your input? It's also confusing that some augmentation (like mask creation) seems to happen in two different places (when generating the lmdb and in the CPM data transformer)

**Comment by mdering** [comment]
@ZheC could you please have a look at this?

**Comment by BeauDoggie** [comment]
您好！，来信收到，尽快给您回复。
