### ISSUE TITLE
python example getting cudnn error 

### ISSUE THREAD

**Issue by Ending2015a** [ZheC/Realtime_Multi-Person_Pose_Estimation#62]
when i run python example i got this error in line "caffe.Net(model['deploy...'].....)":

F0521 14:06:36.175204 31854 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR

do anyone know how to fix this???

ubuntu 16.04 / gtx 1080 / nvidia-381 / cuda 8.0 / cuDNN 6.0 /

**Comment by ZheC** [comment]
Do you compile the caffe with cuDNN support? We are using cuDNN v5.3
