### ISSUE TITLE
how to training  data  by using  Realtime_Multi-Person_Pose_Estimation

### ISSUE THREAD

**Issue by Phoebe-star** [ZheC/Realtime_Multi-Person_Pose_Estimation#69]
I want to train the reverse  of  people
the image is like
 
![image](https://user-images.githubusercontent.com/29423761/27175444-d2602aee-51f1-11e7-9fd1-8c56c3f78c9b.png)

Realtime_Multi-Person_Pose_Estimation  can  not  detect  the reverse  of  people .

**Comment by ZheC** [comment]
When training, you can set max_rotate_degree=180 in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/setLayers.py#L459

The data augmentation will generate the reverse of people example during training
