### ISSUE TITLE
resized_map and joints

### ISSUE THREAD

**Issue by KeyKy** [ZheC/Realtime_Multi-Person_Pose_Estimation#8]
@ZheC I find the resized_map(coco) shape is 1 57 544 960 and 57 means 19 + 38. Does 19 means confidence score of body parts+bgk? What does 38 means (orientation vector [x,y] of each pixel)?

Joints shape is 1 18 65 3. I guess 18 is number of body parts(without background). 65=1+64,  1 is used to represent number of peaks and 64 is the max number of peaks. 3=2+1, here 1 is score of the peak. What makes me confused is 2. which one does it mean? orientation vector [x,y] or position point [x,y]?

**Comment by ZheC** [comment]
19 = 18 parts + 1 bkg. 38 = 19x2 PAFs (orientation vectors [x,y]). 

2 is the position [x,y]
