### ISSUE TITLE
Tensorflow implementation

### ISSUE THREAD

**Issue by Zumbalamambo** [ZheC/Realtime_Multi-Person_Pose_Estimation#80]
Is there any Tensorflow / keras implementation of this?

**Comment by dragonfly90** [comment]
https://github.com/raymon-tian/keras_Realtime_Multi-Person_Pose_Estimation

**Comment by ZheC** [comment]
https://github.com/michalfaber/keras_Realtime_Multi-Person_Pose_Estimation

**Comment by ildoonet** [comment]
https://github.com/ildoonet/tf-openpose
