### ISSUE TITLE
How label data are generated 

### ISSUE THREAD

**Issue by yataoz** [ZheC/Realtime_Multi-Person_Pose_Estimation#81]
Hi Zhe Cao, 

Can you point me to the piece of code where you generate the label data, i.e., ground truth confidence maps and part affinity fields. I thought it could be in genLMDB, but couldn't find it. 

Thanks in advance,
@ZheC

**Comment by ZheC** [comment]
In LMDB we only store the keypoint locations. The code to generate GT confidence maps and part affinity fields is in our data reading later https://github.com/CMU-Perceptual-Computing-Lab/caffe_train/blob/master/src/caffe/cpm_data_transformer.cpp of caffe_train https://github.com/CMU-Perceptual-Computing-Lab/caffe_train
