### ISSUE TITLE
Where Can I download the trained weights?

### ISSUE THREAD

**Issue by xhzcyc** [ZheC/Realtime_Multi-Person_Pose_Estimation#84]
Hi, 
Where Can I download the trained weights? 
It's the file model/_trained_COCO/pose_iter_440000.caffemodel
Thanks

**Comment by vipuldivyanshu92** [comment]
trained COCO => http://posefs1.perception.cs.cmu.edu/Users/ZheCao/pose_iter_440000.caffemodel
trained_MPI => http://posefs1.perception.cs.cmu.edu/Users/ZheCao/pose_iter_146000.caffemodel

**Comment by neerajvashistha** [comment]
Hi,
it is ERROR 404: Not Found.

> trained COCO => http://posefs1.perception.cs.cmu.edu/Users/ZheCao/pose_iter_440000.caffemodel
> trained_MPI => http://posefs1.perception.cs.cmu.edu/Users/ZheCao/pose_iter_146000.caffemodel

**Comment by andrewgenesis** [comment]
I am getting a 404 error as well.

**Comment by gormonn** [comment]
@neerajvashistha
@andrewgenesis
Try this link:
https://github.com/foss-for-synopsys-dwc-arc-processors/synopsys-caffe-models/raw/master/caffe_models/openpose/caffe_model/pose_iter_440000.caffemodel
