### ISSUE TITLE
Can I train the model without MATLAB

### ISSUE THREAD

**Issue by Nestarneal** [ZheC/Realtime_Multi-Person_Pose_Estimation#89]
Hi,
It seems that I need to use MATLAB to convert the annotations so that I can train my own model.
Is there any solution that I can achieve the same task without MATLAB? 
Many thanks.

**Comment by gineshidalgo99** [comment]
Unfortunately not, unless the Matlab code is entirely translated to Python.

**Comment by SBoulanger** [comment]
I might be wrong but can't we just download the LMDB from your link then start training with that?
