### ISSUE TITLE
About 'cpm_transform_param'

### ISSUE THREAD

**Issue by NIEYALI** [ZheC/Realtime_Multi-Person_Pose_Estimation#9]
thanks for your share, but when I use 'train_pose.sh', It gave me error following:

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 11:23: Message type "caffe.LayerParameter" has no field named "cpm_transform_param".
F0206 11:29:26.923185  7789 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: pose_train_test.prototxt

Could you help me?
Thank you very much

**Comment by KeyKy** [comment]
I found these code in caffe.proto. I guess author move cpm_transform_param to transform_param.
message TransformationParameter {
  // For data pre-processing, we can do simple scaling and subtracting the
  // data mean, if provided. Note that the mean subtraction is always carried
  // out before scaling.
  optional float scale = 1 [default = 1];
  // Specify if we want to randomly mirror data.
  optional bool mirror = 2 [default = false];
  // Specify if we would like to randomly crop an image.
  optional uint32 crop_size = 3 [default = 0];
  // mean_file and mean_value cannot be specified at the same time
  optional string mean_file = 4;
  // if specified can be repeated once (would substract it from all the channels)
  // or can be repeated the same number of times as channels
  // (would subtract them from the corresponding channel)
  repeated float mean_value = 5;
  optional uint32 stride = 6 [default = 4];
  optional float scale_cvg = 7 [default = 0.5];
  optional uint32 max_cvg_len = 8 [default = 50];
  optional uint32 min_cvg_len = 9 [default = 50];
  optional bool opaque_coverage = 10 [default = true];
  optional string coverage = 11 [default = "gridbox_max"];
  optional float flip_prob = 12 [default = 0.5];
  optional float max_rotate_degree = 13 [default = 5.0];
  optional bool visualize = 14 [default = false];
  optional uint32 crop_size_x = 15 [default = 368];
  optional uint32 crop_size_y = 16 [default = 368];
  optional float scale_prob = 17 [default = 0.5];
  optional float scale_min = 18 [default = 0.9];
  optional float scale_max = 19 [default = 1.1];
  optional float bbox_norm_factor = 20 [default = 300];
  optional string img_header = 21 [default = "."];
  // Force the decoded image to have 3 color channels.
  optional bool force_color = 22 [default = false];
  // Force the decoded image to have 1 color channels.
  optional bool force_gray = 23 [default = false];
  optional float target_dist = 24 [default = 1.0];
  optional float center_perterb_max = 25 [default = 10.0];
  optional float sigma = 26 [default = 7.0];
  optional float sigma_center = 27 [default = 21.0];
  optional float clahe_tile_size = 28 [default = 8.0];
  optional float clahe_clip_limit = 29 [default = 4.0];
  optional bool do_clahe = 30 [default = false];
  optional uint32 num_parts = 31 [default = 14];
  optional uint32 num_total_augs = 32 [default = 82];
  optional string aug_way = 33 [default = "rand"];
  optional uint32 gray = 34 [default = 0];
  optional uint32 np_in_lmdb = 35 [default = 16];
  optional bool transform_body_joint = 38 [default = true];
}

**Comment by NIEYALI** [comment]
Thanks for your kindness

**Comment by NIEYALI** [comment]
@KeyKy Could you train now? when I use caffe_train, compiling has some problem, I can't 'make all' so other work can not continue. Could you help me to find the problem?

**Comment by KeyKy** [comment]
Not yet, I also have compiling problem because i use cudnn v5 and the caffe_train may be too old to compile. Now i am rewriting the test code.

**Comment by NIEYALI** [comment]
Thanks a lot, I use cudnn v4 and opencv3.1. If you solve the problem, Please inform me , Thank you very much.

**Comment by ZheC** [comment]
@KeyKy I have fixed the issue with an updated caffe_train (https://github.com/CMU-Perceptual-Computing-Lab/caffe_train). Also, it uses a newer version of caffe so that it is compatible with CUDA 7.5/ 8.0 and cudnn v5. Let me know if you meet other issues.
