### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by vijay1131** [ZheC/Realtime_Multi-Person_Pose_Estimation#90]
Hi I am getting this error. while running the demo.ipynb
heatmap_avg = heatmap_avg + heatmap / len(multiplier)
ValueError: operands could not be broadcast together with shapes (674,712,19) (674,712,16) 

I see that heatmap_avg has been defined like this
heatmap_avg = np.zeros((oriImg.shape[0], oriImg.shape[1], 19))

how should i deal with this?

**Comment by dingyiwei** [comment]
Hi @vijay1131 , how did you solve that problem?
I got the similar error "... with shapes (674, 712, 19) (674, 712, 38)". I am trying to change the number 19 to 38 directly, but I seem to get wrong results, since heatmaps shown are not like those in demo.ipynb originally.
Could you show your solutions?

**Comment by LoveUrfuNo** [comment]
same problem

**Comment by chaomaer** [comment]
@dingyiwei 
Do you find the solution? I delete the `__pycache__`dir, and restart the demo, it works, hope this helps you.

**Comment by vijay1131** [comment]
Using the latest repo solved the issue.

**Comment by utisolichah** [comment]
how solve this problem? thank you

**Comment by royshelly1008** [comment]
I am getting the same error with the latest repo. Please help. Thank You

**Comment by leezhang2** [comment]
I delete the __pycache__dir, and restart the demo, also using the latest repo ,but it doesn't work. Anyone can help me, thankyou

**Comment by Sigmadsen** [comment]
1. I've deleted __pycache__ dir. 
2. Try to rerun script in google colab 5 times and it has helped for me.

But after some time (30 min) error was returned. Then I need redo previous steps periodically.

**Comment by siyuhuang** [comment]
Run script with `print(output_blobs.keys())`

You will find that the dict keys are randomly sorted. Just change `list(output_blobs.keys())[1]` and 'list(output_blobs.keys())[0]' to `Mconv7_stage6_L2` and `Mconv7_stage6_L2`, respectively

**Comment by simoooooooon** [comment]
> Run script with `print(output_blobs.keys())`
> 
> You will find the dict keys are randomly sorted every time (python3).
> 
> Just change `list(output_blobs.keys())[1]` and `list(output_blobs.keys())[0]` to `'Mconv7_stage6_L2'` and `'Mconv7_stage6_L2'`, respectively.

It works for me, I change  `list(output_blobs.keys())[1]` and `list(output_blobs.keys())[0]` to `'Mconv7_stage6_L2'` and `'Mconv7_stage6_L1'`,
