### ISSUE TITLE
whatis the meaning of  np = 56    # num_parts

### ISSUE THREAD

**Issue by xiangweifeng** [ZheC/Realtime_Multi-Person_Pose_Estimation#93]

**Comment by feitiandemiaomi** [comment]
@xiangweifeng  Hi, I also  wonder what is the meaning of np =56,   And ,what does  np=56 has to do with np_in_lmdb=17  , could  you tell me ?

**Comment by feitiandemiaomi** [comment]
@xiangweifeng   Thanks for your reply , It is very cool !

**Comment by noirmist** [comment]
@xiangweifeng Thank you for your great explanation. I found that you are using mid_1[12] and mid_2[12]. (Guess these are left shoulder and left ear.) I'm curious that why you generate PAF between two of them, could you tell me?

**Comment by xiangweifeng** [comment]
That'not my definition, it's authour's. I think it can improve the stability of the PAF. You can define any kind of correpondence.

**Comment by noirmist** [comment]
I see. thank you a lot!

2017-09-16 17:26 GMT+09:00 xiangweifeng <notifications@github.com>:

**Comment by liaowang0125** [comment]
What is mid_1 and mid_2 mean?
```
int mid_1[19] = {2, 9, 10, 2, 12, 13, 2, 3, 4, 3, 2, 6, 7, 6, 2, 1, 1, 15, 16};
int mid_2[19] = {9, 10, 11, 12, 13, 14, 3, 4, 5, 17, 6, 7, 8, 18, 1, 15, 16, 17, 18};
```

**Comment by USTClj** [comment]
@liaowang0125  Have you figured it out?  Someone can kindly explain that?

**Comment by liaowang0125** [comment]
@USTClj   19 connecting limbs
