### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by xiangweifeng** [ZheC/Realtime_Multi-Person_Pose_Estimation#94]
dell@dell-Precision-Tower-7910:/media/dell/software/dataset/COCO$ python genLMDB.py
COCO
126395
121522
/media/dell/software/dataset/COCO/images/train2014/COCO_train2014_000000467746.jpg
Traceback (most recent call last):
  File "genLMDB.py", line 196, in <module>
    writeLMDB(['COCO'], '/media/dell/software/dataset/COCO/COCO_kpt/lmdb', 1)
  File "genLMDB.py", line 80, in writeLMDB
    height = img.shape[0]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by aseaday** [comment]
You should change the directory of COCO in the getLMDB.py

**Comment by xiangweifeng** [comment]
Thank you.

**Comment by salvador-blanco** [comment]
@aseaday I have changed the directory, but now I get the following error.
I would appreciate if you could help 
Thanks
```
python genLMDB.py
COCO
126395
121522
/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/images/train2014/COCO_train2014_000000135820.jpg
train2014/COCO_train2014_000000135820.jpg
000000135820.
COCO
Traceback (most recent call last):
  File "genLMDB.py", line 198, in <module>
    writeLMDB(['COCO'], '/home/chava/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training/dataset/COCO/lmdb', 1)
  File "genLMDB.py", line 171, in writeLMDB
    img4ch = np.concatenate((img, meta_data, mask_miss[...,None], mask_all[...,None]), axis=2)
TypeError: 'NoneType' object has no attribute '__getitem__'
(caffetmp) chava@VC82620v4:~/Documents/OpenPose/Realtime_Multi-Person_Pose_Estimation-master/training$ 

```
