### ISSUE TITLE
About image feature size

### ISSUE THREAD

**Issue by NIEYALI** [ZheC/Realtime_Multi-Person_Pose_Estimation#99]
Hi, dear Cao,
Thanks for your great work, I have one question about the output image feature size. In your work you made output size is 46, but if make it be 23 or smaller , the program will have problem. Could you tell me in the codes, where to change the size except model part?

Thanks a lot

**Comment by anatolix** [comment]
It controlled by the stride parameter in config/C++ caffe layer.  
368 / 8 = 46

**Comment by NIEYALI** [comment]
@anatolix Thanks for your reply. But could u tell me detail about the path to find it? Thanks a lot.

**Comment by ZheC** [comment]
Sorry for the late response. For your question about the path, it is in https://github.com/ZheC/Realtime_Multi-Person_Pose_Estimation/blob/master/training/example_proto/pose_train_test.prototxt#L11-L25
